services:
  postgres:
    image: postgres:13
    container_name: nyc_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ny_taxi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project1-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ny_taxi"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: nyc_pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - project1-network
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    
networks:
  project1-network:
    name: project1-network
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:

